// eslint-disable-next-line
const crmData = {
  topData: ["112,400", "212", "105", "112,400", "150", "1,105"],

  statisticsGraph: {
    projectData: [
      { month: "1월", number: 110 },
      { month: "2월", number: 280 },
      { month: "3월", number: 120 },
      { month: "4월", number: 290 },
      { month: "5월", number: 140 },
      { month: "6월", number: 320 },
      { month: "7월", number: 240 },
      { month: "8월", number: 400 },
      { month: "9월", number: 270 },
      { month: "10월", number: 450 },
      { month: "11월", number: 280 },
      { month: "12월", number: 430 },
    ],
    clientsData: [
      { month: "1월", number: 20 },
      { month: "2월", number: 170 },
      { month: "3월", number: 40 },
      { month: "4월", number: 200 },
      { month: "5월", number: 70 },
      { month: "6월", number: 270 },
      { month: "7월", number: 100 },
      { month: "8월", number: 310 },
      { month: "9월", number: 130 },
      { month: "10월", number: 350 },
      { month: "11월", number: 170 },
      { month: "12월", number: 400 },
    ],
    incomeData: [
      { month: "1월", number: 110 },
      { month: "2월", number: 230 },
      { month: "3월", number: 100 },
      { month: "4월", number: 290 },
      { month: "5월", number: 160 },
      { month: "6월", number: 320 },
      { month: "7월", number: 220 },
      { month: "8월", number: 450 },
      { month: "9월", number: 260 },
      { month: "10월", number: 490 },
      { month: "11월", number: 240 },
      { month: "12월", number: 400 },
    ],
  },
  noticeList: [
    {
      title: "스마트 베타 메시지 서비스 설문조사",
      writer: "최대표",
      regDate: "2022.4.26",
    },
    {
      title: "말풍선 알림 업데이트 안내 v1.0",
      writer: "최대표",
      regDate: "2022.4.26",
    },
    {
      title: "채널 관리자 소폭 개편했습니다",
      writer: "최고관리자",
      regDate: "2022.4.26",
    },
    {
      title: "[복구오완료]서비스 장애 안내]",
      writer: "최고관리자",
      regDate: "2022.4.26",
    },
    {
      title: "개발자용 채널 생성 프로필 기능 안내",
      writer: "최대표",
      regDate: "2022.4.26",
    },
    {
      title: "DB 백업을 위한 서비스 일시 정지 일정 발표",
      writer: "최대표",
      regDate: "2022.4.26",
    },
  ],
  todayTaskData: [
    {
      id: 1,
      task: "Send the Billing Agreement",
      date: "24 Mar, 2019",
      isChecked: false,
    },
    {
      id: 2,
      task: "Send over all the documentation",
      date: "24 Mar, 2019",
      isChecked: false,
    },
    {
      id: 3,
      task: "Call Adam to review the documentation",
      date: "24 Mar, 2019",
      isChecked: true,
    },
    {
      id: 4,
      task: "Meeting with Daron to review the intake form",
      date: "24 Mar, 2019",
      isChecked: false,
    },
    {
      id: 5,
      task: "Call Matthew to schedule an interview",
      date: "24 Mar, 2019",
      isChecked: false,
    },
    {
      id: 6,
      task: "checking UiKings CremaThemeProvider and give customer support",
      date: "24 Mar, 2019",
      isChecked: false,
    },
    {
      id: 7,
      task: "go to market to buy baby corn",
      date: "24 Mar, 2019",
      isChecked: false,
    },
    {
      id: 8,
      task: "schedule a meeting with team alpha",
      date: "24 Mar, 2019",
      isChecked: false,
    },
  ],
  websiteTrafficData: [
    { month: "1월", users: 1000 },
    { month: "2월", users: 600 },
    { month: "3월", users: 1100 },
    { month: "4월", users: 900 },
    { month: "5월", users: 1000 },
    { month: "6월", users: 500 },
    { month: "7월", users: 900 },
    { month: "8월", users: 800 },
    { month: "9월", users: 900 },
    { month: "10월", users: 750 },
    { month: "11월", users: 700 },
    { month: "12월", users: 900 },
  ],
};
export default crmData;
